repositories:
  OpenTelemetry:
    - https://github.com/open-telemetry/opentelemetry-ruby
    - https://github.com/open-telemetry/opentelemetry-ruby-contrib
  Gem:
    - https://github.com/lostisland/faraday
    - https://github.com/fog/fog-google
    - https://github.com/ruby-grape/grape
    - https://github.com/puma/puma
    - https://github.com/varvet/pundit
  Test:
    - https://github.com/zdennis/activerecord-import
    - https://github.com/citusdata/activerecord-multi-tenant
    - https://github.com/brendon/acts_as_list
    - https://github.com/sporkmonger/addressable
    - https://github.com/stefankroes/ancestry
    - https://github.com/bdewater/android_key_attestation
    - https://github.com/davidcelis/api-pagination
    - https://github.com/Gusto/apollo-federation-ruby
    - https://github.com/DataWraith/ascii85gem/
    - https://github.com/rumblelabs/asset_sync
    - https://github.com/barsoom/attr_extras
    - https://github.com/awesome-print/awesome_print
    - https://github.com/dkubb/axiom-types
    - https://github.com/ruby/base64
    - https://github.com/bcrypt-ruby/bcrypt-ruby
    - https://github.com/BetterErrors/better_errors
    - https://github.com/Shopify/better-html
    - https://github.com/ruby/bigdecimal
    - https://github.com/dmendel/bindata
    - https://github.com/banister/binding_of_caller
    - https://github.com/Shopify/bootsnap
    - https://github.com/fnando/browser
    - https://github.com/rails/builder
    - https://github.com/flyerhzm/bullet
    - https://github.com/teamcapybara/capybara
    - https://github.com/carrierwaveuploader/carrierwave
    - https://github.com/enkessler/childprocess
    - https://github.com/hpoydar/chronic_duration
    - https://github.com/wvanbergen/chunky_png/wiki
    - https://github.com/CocoaPods/CLAide
    - https://github.com/cocoapods/claide-plugins
    - https://github.com/solnic/coercible
    - https://github.com/interagent/committee
    - https://github.com/willnet/committee-rails
    - https://github.com/mperham/connection_pool
    - https://github.com/Shopify/constant_resolver
    - https://github.com/CocoaPods/Cork
    - https://github.com/cedarcode/cose-ruby
    - https://github.com/countries/countries
    - https://github.com/danmayer/coverband
    - https://github.com/jnunemaker/crack
    - https://github.com/rgrove/crass/
    - https://github.com/ruby/csv
    - https://github.com/danger/danger
    - https://github.com/ruby/date
    - https://github.com/ruby/debug
    - https://github.com/banister/debug_inspector
    - https://github.com/apotonick/declarative
    - https://github.com/dkubb/descendants_tracker
    - https://github.com/heartcombo/devise
    - https://github.com/tigrish/devise-i18n
    - https://github.com/tinfoil/devise-two-factor
    - https://github.com/tknzk/devise_alt_timeoutable
    - https://github.com/scambra/devise_invitable
    - https://github.com/halostatue/diff-lcs
    - https://github.com/postmodern/digest-crc#readme
    - https://github.com/knu/ruby-domain_name
    - https://github.com/bkeepers/dotenv
    - https://github.com/ruby/drb
    - https://github.com/contribsys/einhorn
    - https://github.com/K-and-R/email_validator
    - https://github.com/zmbacker/enum_help
    - https://github.com/tomiacannondale/era_ja
    - https://github.com/jeremyevans/erubi
    - https://github.com/Shopify/event_stream_parser
    - https://github.com/excon/excon
    - https://github.com/thoughtbot/factory_bot
    - https://github.com/thoughtbot/factory_bot_rails
    - https://github.com/faker-ruby/faker
    - https://github.com/guilleiguaran/fakeredis
    - https://github.com/lostisland/faraday-em_http
    - https://github.com/lostisland/faraday-em_synchrony
    - https://github.com/lostisland/faraday-excon
    - https://github.com/sourcelevel/faraday-http-cache
    - https://github.com/lostisland/faraday-httpclient
    - https://github.com/lostisland/faraday-multipart
    - https://github.com/lostisland/faraday-net_http
    - https://github.com/lostisland/faraday-net_http_persistent
    - https://github.com/lostisland/faraday-patron
    - https://github.com/lostisland/faraday-rack
    - https://github.com/lostisland/faraday-retry
    - https://github.com/ffi/ffi/wiki
    - https://github.com/musaffa/file_validators
    - https://github.com/fog/fog-core
    - https://github.com/fog/fog-google
    - https://github.com/fog/fog-xml
    - https://github.com/geemus/formatador
    - https://github.com/googleapis/gapic-generator-ruby
    - https://github.com/willnet/gimei
    - https://github.com/gazay/gon
    - https://github.com/google/google-api-ruby-client
    - https://github.com/google/google-api-ruby-client
    - https://github.com/google/google-api-ruby-client
    - https://github.com/google/google-api-ruby-client
    - https://github.com/google/google-api-ruby-client
    - https://github.com/google/google-api-ruby-client
    - https://github.com/google/google-api-ruby-client
    - https://github.com/google/google-api-ruby-client
    - https://github.com/googleapis/google-cloud-ruby
    - https://github.com/googleapis/google-cloud-ruby
    - https://github.com/googleapis/google-cloud-ruby/tree/master/google-c
    - https://github.com/googleapis/ruby-cloud-env
    - https://github.com/googleapis/google-cloud-ruby/tree/master/google-c
    - https://github.com/googleapis/google-cloud-ruby
    - https://github.com/googleapis/google-cloud-ruby
    - https://github.com/googleapis/google-cloud-ruby
    - https://github.com/googleapis/google-cloud-ruby
    - https://github.com/googleapis/google-cloud-ruby/tree/master/google-c
    - https://github.com/googleapis/ruby-core-libraries
    - https://github.com/googleapis/common-protos-ruby
    - https://github.com/googleapis/common-protos-ruby
    - https://github.com/googleapis/google-auth-library-ruby
    - https://github.com/ruby-grape/grape
    - https://github.com/ruby-grape/grape-entity
    - https://github.com/ruby-grape/grape-swagger
    - https://github.com/ruby-grape/grape-swagger-entity
    - https://github.com/ruby-grape/grape-swagger-rails
    - https://github.com/rmosolgo/graphql-ruby
    - https://github.com/Shopify/graphql-batch
    - https://github.com/google/grpc/tree/master/src/ruby
    - https://github.com/google/grpc/tree/master/src/ruby/tools
    - https://github.com/k0kubun/hamlit
    - https://github.com/mfung/hamlit-rails
    - https://github.com/liufengyun/hashdiff
    - https://github.com/ianheggie/health_check
    - https://github.com/ioquatix/http-accept
    - https://github.com/sparklemotion/http-cookie
    - https://github.com/nahi/httpclient
    - https://github.com/ruby-i18n/i18n
    - https://github.com/dkubb/ice_nine
    - https://github.com/ruby/io-console
    - https://github.com/ruby/irb
    - https://github.com/rails/jbuilder
    - https://github.com/chocoby/jp_prefecture
    - https://github.com/rails/jquery-rails
    - https://github.com/thoughtbot/json_matchers
    - https://github.com/brandur/json_schema
    - https://github.com/jwt/ruby-jwt
    - https://github.com/kaminari/kaminari
    - https://github.com/kaminari/kaminari
    - https://github.com/kaminari/kaminari
    - https://github.com/kaminari/kaminari
    - https://github.com/kramdown/parser-gfm
    - https://github.com/mtsmfm/language_server-protocol-ruby
    - https://github.com/copiousfreetime/launchy
    - https://github.com/ryanb/letter_opener
    - https://github.com/fgrehm/letter_opener_web
    - https://github.com/ruby/logger
    - https://github.com/roidrage/lograge
    - https://github.com/flavorjones/loofah
    - https://github.com/mikel/mail
    - https://github.com/rails/marcel
    - https://github.com/ruby/matrix
    - https://github.com/panorama-ed/memo_wise
    - https://github.com/kpumuk/meta-tags
    - https://github.com/mime-types/ruby-mime-types/
    - https://github.com/mime-types/mime-types-data/
    - https://github.com/minimagick/minimagick
    - https://github.com/discourse/mini_mime
    - https://github.com/minitest/minitest
    - https://github.com/raszi/mrkt
    - https://github.com/intridea/multi_json
    - https://github.com/socketry/multipart-post
    - https://github.com/sinatra/mustermann
    - https://github.com/ruby-grape/mustermann-grape
    - https://github.com/ruby/mutex_m
    - https://github.com/Fingertips/nap
    - https://github.com/ruby/net-imap
    - https://github.com/ruby/net-pop
    - https://github.com/ruby/net-protocol
    - https://github.com/ruby/net-smtp
    - https://github.com/geemus/netrc
    - https://github.com/newrelic/newrelic-ruby-agent
    - https://github.com/socketry/nio4r
    - https://github.com/ruby/nkf
    - https://github.com/octokit/octokit.rb
    - https://github.com/ahoward/open4
    - https://github.com/ota42y/openapi_parser
    - https://github.com/ruby/openssl
    - https://github.com/cedarcode/openssl-signature_algorithm
    - https://github.com/ruby/ostruct
    - https://github.com/Shopify/packwerk
    - https://github.com/rubyatscale/packwerk-extensions
    - https://github.com/paper-trail-gem/paper_trail
    - https://github.com/grosser/parallel
    - https://github.com/whitequark/parser
    - https://github.com/yob/pdf-reader
    - https://github.com/ged/ruby-pg
    - https://github.com/mquan/pocky
    - https://github.com/ruby/pp
    - https://github.com/hidakatsuya/prawn-disable_word_break
    - https://github.com/ruby/prettyprint
    - https://github.com/ruby/prism
    - https://github.com/joker1007/proc_to_ast
    - https://github.com/lgierth/promise
    - https://github.com/rweng/pry-rails
    - https://github.com/ruby/pstore
    - https://github.com/ruby/psych
    - https://github.com/varvet/pundit
    - https://github.com/philnash/pwned
    - https://github.com/ruby/racc
    - https://github.com/rack/rack
    - https://github.com/rack/rack-attack
    - https://github.com/cyu/rack-cors
    - https://github.com/dtaniwaki/rack-dev-mark
    - https://github.com/kainosnoema/rack-lineprof
    - https://github.com/rack/rack-session
    - https://github.com/rack/rack-test
    - https://github.com/rack/rackup
    - https://github.com/rails/rails-controller-testing
    - https://github.com/rails/rails-dom-testing
    - https://github.com/rails/rails-html-sanitizer
    - https://github.com/svenfuchs/rails-i18n
    - https://github.com/tenderlove/rails_autolink
    - https://github.com/sickill/rainbow
    - https://github.com/ruby/rake
    - https://github.com/activerecord-hackery/ransack
    - https://github.com/jmhodges/rchardet
    - https://github.com/redis/redis-rb
    - https://github.com/ammar/regexp_parser
    - https://github.com/ruby/reline
    - https://github.com/trailblazer/representable/
    - https://github.com/steveklabnik/request_store
    - https://github.com/madebylotus/request_store-sidekiq
    - https://github.com/heartcombo/responders
    - https://github.com/rest-client/rest-client
    - https://github.com/ruby/rexml
    - https://github.com/vmg/rinku
    - https://github.com/mdp/rotp
    - https://github.com/whomwah/rqrcode
    - https://github.com/whomwah/rqrcode_core
    - https://github.com/rspec/rspec-collection_matchers
    - https://github.com/rspec/rspec-core
    - https://github.com/rspec/rspec-expectations
    - https://github.com/rspec/rspec-mocks
    - https://github.com/rspec-parameterized/rspec-parameterized-core
    - https://github.com/rspec/rspec-rails
    - https://github.com/r7kamura/rspec-request_describer
    - https://github.com/rspec/rspec-support
    - https://github.com/sj26/rspec_junit_formatter
    - https://github.com/rubocop/rubocop
    - https://github.com/rubocop/rubocop-ast
    - https://github.com/rubocop/rubocop-capybara
    - https://github.com/rubocop/rubocop-factory_bot
    - https://github.com/rubocop/rubocop-performance
    - https://github.com/rubocop/rubocop-rails
    - https://github.com/rubocop/rubocop-rspec
    - https://github.com/rubocop/rubocop-rspec_rails
    - https://github.com/glejeune/Ruby-Graphviz
    - https://github.com/alexrudall/ruby-openai
    - https://github.com/jfelchner/ruby-progressbar
    - https://github.com/saml-toolkits/ruby-saml
    - https://github.com/ruby/ruby2_keywords
    - https://github.com/bdewater/safety_net_attestation
    - https://github.com/saml-idp/saml_idp
    - https://github.com/tknzk/saml_idp_metadata
    - https://github.com/sass/sassc-ruby
    - https://github.com/sass/sassc-rails
    - https://github.com/lostisland/sawyer
    - https://github.com/StudistCorporation/scimaenaga
    - https://github.com/argerim/select2-rails
    - https://github.com/getsentry/sentry-ruby/tree/5.22.1/sentry-rails
    - https://github.com/getsentry/sentry-ruby/tree/5.22.1/sentry-ruby
    - https://github.com/getsentry/sentry-ruby/tree/5.22.1/sentry-sidekiq
    - https://github.com/kenaniah/sidekiq-status
    - https://github.com/googleapis/signet
    - https://github.com/heartcombo/simple_form
    - https://github.com/simplecov-ruby/simplecov
    - https://github.com/simplecov-ruby/simplecov-html
    - https://github.com/fede-moya/simplecov_json_formatter
    - https://github.com/rails/spring
    - https://github.com/jonleighton/spring-commands-rspec
    - https://github.com/rails/sprockets
    - https://github.com/rails/sprockets-rails
    - https://github.com/arkadiyt/ssrf_filter
    - https://github.com/googleapis/google-cloud-ruby/tree/master/stackdri
    - https://github.com/rmm5t/strip_attributes
    - https://github.com/soutaro/strong_json
    - https://github.com/ankane/strong_migrations
    - https://github.com/splitwise/super_diff
    - https://github.com/ruby/sync
    - https://github.com/judofyr/temple
    - https://github.com/tj/terminal-table
    - https://github.com/ruby-concurrency/thread_safe
    - https://github.com/jeremyevans/tilt
    - https://github.com/travisjeffery/timecop
    - https://github.com/ruby/timeout
    - https://github.com/flori/tins
    - https://github.com/cedarcode/tpm-key_attestation
    - https://github.com/apotonick/uber
    - https://github.com/hardpixel/unaccent
    - https://github.com/knu/ruby-unf
    - https://github.com/janlelis/unicode-display_width
    - https://github.com/adzap/validates_timeliness
    - https://github.com/solnic/virtus
    - https://github.com/hassox/warden
    - https://github.com/cedarcode/webauthn-ruby
    - https://github.com/bblimke/webmock
    - https://github.com/ruby/webrick
    - https://github.com/faye/websocket-driver-ruby
    - https://github.com/faye/websocket-extensions-ruby
    - https://github.com/schneems/wicked
    - https://github.com/digidentity/xmlenc
    - https://github.com/digidentity/xmlmapper
    - https://github.com/teamcapybara/xpath
    - https://github.com/fxn/zeitwerk
    - https://github.com/zengin-code/zengin-rb
labels:
 - "help wanted"
 - "good first issue"
 - "you can help" # for grape
 - "contrib-wanted" # for puma
 - "You Can Do This"
 - "ðŸŽ’ Beginner Friendly"
 - "up for grabs"
 - "Status: Up for grabs"
 - "Up for grabs"
 - "needs help"
 - "pr-welcome"
 - "need contributor"
 - "easy"
per_page: 100
